### PR TITLE
Enable hostnetwork to allow DLNA functionality

### LINKED ISSUE #62: Host Networking
Is it possible within the Home Assistant Environment to have an option for using Host Networking for this addon? The DLNA Server will not be discovered without the being exposed to the network where the the receivers are.

### PR DESCRIPTION
**Pull request by weidi**
would fix #62

### CODE REVIEW

**Comment by mdvorak** [comment]
Hi, thanks for the PR. I don't have generally problem with this option, but I'd like to explore the possibility to have this enabled by configuration, instead of enabling it for everyone. Using host network has security implications.

**Comment by OtisPresley** [comment]
Thnaks @weidi and @mdvorak! I agree that this is better as a configuration option as not everyone will use DLNA functionality.

**Comment by mdvorak** [comment]
I'll get to it next week

**Comment by mdvorak** [comment]
Resolved in https://github.com/mdvorak/ha-addon-jellyfin/commit/b1b6a806f6842b576b052045da4067e546509bf5

**Comment by OtisPresley** [comment]
Thanks @mdvorak! I just uninstalled in HA and installed the version with host networking, and it works perfectly. Thank you!

**Pull request closed without merging**
